apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unihelm.fullname" . }}
  labels:
    {{- include "unihelm.labels" . | nindent 4 }}
data:
  {{- range $.Values.envs.asConfigMap }}
  {{ regexReplaceAllLiteral "(-{1})" .var_name "___" | quote }}:   {{ .var_value | quote }}
  {{- end }}    
