apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unihelm.fullname" . }}
  labels:
    {{- include "unihelm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $.Values.envs.asSecret }}
  {{ regexReplaceAllLiteral "(-)" .var_name "___" | quote }}:   {{ .var_value | default (randAlphaNum 40)| b64enc | quote }}
  {{- end }}



