apiVersion: v1
kind: Service
metadata:
  name: {{ include "unihelm.fullname" . }}
  labels:
    {{- include "unihelm.labels" . | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "unihelm.selectorLabels" . | nindent 4 }}
