apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unichart.fullname" . }}
  labels:
    {{- include "unichart.labels" . | nindent 4 }}
data:
  {{- range $.Values.envs }}
  {{ regexReplaceAllLiteral "(-{1})" .var_name "___" | quote }}:   {{ .var_value | quote }}
  {{- end }}    
  