{{- if $.Values.ingressRoutes.enabled -}}
{{- $fullName := include "unichart.fullname" $ -}}
{{- $svcPort := $.Values.service.port -}}
{{- range $.Values.ingressRoutes.paths }}
---
apiVersion: {{ $.Values.ingressRoutes.apiVersion }}
kind: IngressRoute
metadata:
  name: {{ $fullName }}-{{ .name }}-route
  labels:
    {{- include "unichart.labels" $ | nindent 4 }}
spec:
  entryPoints:
    - {{ .entrypoint | default "websecure" | quote }}
  routes:
    - match: {{ .match }}
      kind: Rule
      {{- if .prefixRewrite -}}
      prefixRewrite: {{ .prefixRewrite | quote}}
      {{- end }}
      services:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
  {{- if .tlsSecret }}
  tls:
    secretName: {{ .tlsSecret }}
  {{- end }}
{{- end }}
{{- end }}
