apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unichart.fullname" . }}
  labels:
    {{- include "unichart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $.Values.secrets }}
  {{ regexReplaceAllLiteral "(-{1})" .sec_name "___" | quote }}:   {{ .sec_value | default (randAlphaNum 40)| b64enc | quote }}
  {{- end }}    
  


